GymAssignment/GymAssignment/Controllers/CourseListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GymAssignment.Data;
using GymAssignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace GymAssignment.Controllers
{
    [Authorize] //(Roles ="Admin")]
    public class CourseListsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CourseListsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CourseLists
        public async Task<IActionResult> Index()
        {
            return View(await _context.CourseList.ToListAsync());
        }

        // GET: CourseLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courseList = await _context.CourseList
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courseList == null)
            {
                return NotFound();
            }

            return View(courseList);
        }

        // GET: CourseLists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CourseLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseName,PhysicalActivity,Time,Instructor,Location")] CourseList courseList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(courseList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(courseList);
        }

        // GET: CourseLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courseList = await _context.CourseList.FindAsync(id);
            if (courseList == null)
            {
                return NotFound();
            }
            return View(courseList);
        }

        // POST: CourseLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CourseName,PhysicalActivity,Time,Instructor,Location")] CourseList courseList)
        {
            if (id != courseList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(courseList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseListExists(courseList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(courseList);
        }

        // GET: CourseLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courseList = await _context.CourseList
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courseList == null)
            {
                return NotFound();
            }

            return View(courseList);
        }

        // POST: CourseLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var courseList = await _context.CourseList.FindAsync(id);
            _context.CourseList.Remove(courseList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseListExists(int id)
        {
            return _context.CourseList.Any(e => e.Id == id);
        }
    }
}

GymAssignment/GymAssignment/Controllers/TimeOffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GymAssignment.Data;
using GymAssignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace GymAssignment.Controllers
{               //Commenting out the roles as we do not have authentication
    [Authorize] //(Roles ="Admin")]
    public class TimeOffController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TimeOffController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TimeOff
        public async Task<IActionResult> Index()
        {
            return View(await _context.TimeOffSchedule.ToListAsync());
        }

        // GET: TimeOff/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeOffSchedule = await _context.TimeOffSchedule
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeOffSchedule == null)
            {
                return NotFound();
            }

            return View(timeOffSchedule);
        }

        // GET: TimeOff/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TimeOff/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Date,CoveredBy,PostTime")] TimeOffSchedule timeOffSchedule)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timeOffSchedule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(timeOffSchedule);
        }

        // GET: TimeOff/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeOffSchedule = await _context.TimeOffSchedule.FindAsync(id);
            if (timeOffSchedule == null)
            {
                return NotFound();
            }
            return View(timeOffSchedule);
        }

        // POST: TimeOff/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Date,CoveredBy,PostTime")] TimeOffSchedule timeOffSchedule)
        {
            if (id != timeOffSchedule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeOffSchedule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeOffScheduleExists(timeOffSchedule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(timeOffSchedule);
        }

        // GET: TimeOff/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeOffSchedule = await _context.TimeOffSchedule
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeOffSchedule == null)
            {
                return NotFound();
            }

            return View(timeOffSchedule);
        }

        // POST: TimeOff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var timeOffSchedule = await _context.TimeOffSchedule.FindAsync(id);
            _context.TimeOffSchedule.Remove(timeOffSchedule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeOffScheduleExists(int id)
        {
            return _context.TimeOffSchedule.Any(e => e.Id == id);
        }
    }
}

GymAssignment/GymAssignment/Controllers/UsersTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GymAssignment.Data;
using GymAssignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace GymAssignment.Controllers
{
    [Authorize]
    public class UsersTableController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersTableController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UsersTable
        public async Task<IActionResult> Index()
        {
            return View(await _context.UsersTable.ToListAsync());
        }

        // GET: UsersTable/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usersTable = await _context.UsersTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usersTable == null)
            {
                return NotFound();
            }

            return View(usersTable);
        }

        // GET: UsersTable/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UsersTable/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,PhoneNumber,StartingWeight,GoalWeight,Location,PreferredTraining")] UsersTable usersTable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usersTable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usersTable);
        }

        // GET: UsersTable/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usersTable = await _context.UsersTable.FindAsync(id);
            if (usersTable == null)
            {
                return NotFound();
            }
            return View(usersTable);
        }

        // POST: UsersTable/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,PhoneNumber,StartingWeight,GoalWeight,Location,PreferredTraining")] UsersTable usersTable)
        {
            if (id != usersTable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usersTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersTableExists(usersTable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usersTable);
        }

        // GET: UsersTable/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usersTable = await _context.UsersTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usersTable == null)
            {
                return NotFound();
            }

            return View(usersTable);
        }

        // POST: UsersTable/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usersTable = await _context.UsersTable.FindAsync(id);
            _context.UsersTable.Remove(usersTable);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersTableExists(int id)
        {
            return _context.UsersTable.Any(e => e.Id == id);
        }
    }
}

GymAssignment/GymAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GymAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Heebo&display=swap" rel="stylesheet">
    <style>
        /* <!-- Added more css for body - Mason --> */
        body, html {
            height: 100%;
            width: 100%;
            font-family: 'Heebo', sans-serif;
        }
        /* <!-- Additional styling added -->  From Kyle*/
        .navbar {
            background-color: #FF8700 !important;
            padding: 1rem;
        }


        .navbar-nav li a {
            color: black !important;
            font-weight: bold;
            text-transform: uppercase;
        }

        .carousel-inner {
            padding-bottom: 2rem;
        }

        .carousel-caption p {
            font-size: 30px;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
        }

        .btn-default {
            background-color: #FF8700 !important;
            border: 1px solid #FF8700 !important;
        }

        .col-md-3 h2 {
            color: #FF8700 !important;
            text-align: center;
            text-transform: uppercase;
            font-weight: bold;
        }

        .img1 {
            width: 100%;
            height: 50%;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>MakeOrBreak</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><strong> Home</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About"><strong> About </strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UsersTable" asp-action=""><strong> Users</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CourseLists" asp-action=""><strong> Sign Up For Courses</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FacultyLists" asp-action=""><strong> View Staff Directory</strong><br /><font color="white">(Staff Only)</font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeOff" asp-action=""><strong>Book Time Off</strong><br /><font color="white">(Staff Only)</font></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MakeOrBreak Fitness- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
